---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-2
  namespace: default
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
    "helm.sh/hook-weight": "-1"
data:
  dummy.config: |
    foo: bar
